// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findNearbyIncidents = `-- name: FindNearbyIncidents :many
SELECT
    id::text AS id,
    incident_type::text AS incident_type,
    CAST(status AS VARCHAR) AS status,
    latitude::float8 AS latitude,
    longitude::float8 AS longitude,
    address_detail,
    COALESCE(reporter_trust_label, 'unverified')::text AS reporter_trust_label,
    to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS created_at,
    (
        6371 * acos(
            LEAST(1.0, cos(radians($1::float8)) * cos(radians(latitude)) *
            cos(radians(longitude) - radians($2::float8)) +
            sin(radians($1::float8)) * sin(radians(latitude)))
        )
    )::float8 AS distance_km,
    COALESCE(photo_paths, ARRAY[]::text[])::text[] AS photo_paths,
    audio_path
FROM incidents
WHERE status NOT IN ('resolved', 'false_alarm', 'canceled')
  AND reporter_id != $3::uuid
  AND NOT EXISTS (
    SELECT 1 FROM incident_responses ir2
    WHERE ir2.incident_id = incidents.id
      AND ir2.responder_id = $3::uuid
      AND ir2.status IN ('waiting_review', 'completed', 'on_scene')
  )
  AND (
    6371 * acos(
        LEAST(1.0, cos(radians($1::float8)) * cos(radians(latitude)) *
        cos(radians(longitude) - radians($2::float8)) +
        sin(radians($1::float8)) * sin(radians(latitude)))
    )
  ) <= $4::float8
ORDER BY distance_km ASC
`

type FindNearbyIncidentsParams struct {
	Lat         float64
	Lng         float64
	VolunteerID pgtype.UUID
	RadiusKm    float64
}

type FindNearbyIncidentsRow struct {
	ID                 string
	IncidentType       string
	Status             string
	Latitude           float64
	Longitude          float64
	AddressDetail      pgtype.Text
	ReporterTrustLabel string
	CreatedAt          string
	DistanceKm         float64
	PhotoPaths         []string
	AudioPath          pgtype.Text
}

func (q *Queries) FindNearbyIncidents(ctx context.Context, arg FindNearbyIncidentsParams) ([]FindNearbyIncidentsRow, error) {
	rows, err := q.db.Query(ctx, findNearbyIncidents,
		arg.Lat,
		arg.Lng,
		arg.VolunteerID,
		arg.RadiusKm,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindNearbyIncidentsRow
	for rows.Next() {
		var i FindNearbyIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.IncidentType,
			&i.Status,
			&i.Latitude,
			&i.Longitude,
			&i.AddressDetail,
			&i.ReporterTrustLabel,
			&i.CreatedAt,
			&i.DistanceKm,
			&i.PhotoPaths,
			&i.AudioPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveResponseByVolunteer = `-- name: GetActiveResponseByVolunteer :one
SELECT
    ir.id::text       AS response_id,
    i.id::text        AS incident_id,
    i.incident_type::text AS incident_type,
    CAST(ir.status AS VARCHAR) AS status,
    i.latitude::float8  AS reporter_latitude,
    i.longitude::float8 AS reporter_longitude,
    i.address_detail,
    CAST(ir.accepted_at AS VARCHAR) AS accepted_at
FROM incident_responses ir
JOIN incidents i ON i.id = ir.incident_id
WHERE ir.responder_id = $1::uuid
  AND ir.status IN ('on_scene', 'waiting_review')
ORDER BY ir.accepted_at DESC
LIMIT 1
`

type GetActiveResponseByVolunteerRow struct {
	ResponseID        string
	IncidentID        string
	IncidentType      string
	Status            string
	ReporterLatitude  float64
	ReporterLongitude float64
	AddressDetail     pgtype.Text
	AcceptedAt        string
}

func (q *Queries) GetActiveResponseByVolunteer(ctx context.Context, volunteerID pgtype.UUID) (GetActiveResponseByVolunteerRow, error) {
	row := q.db.QueryRow(ctx, getActiveResponseByVolunteer, volunteerID)
	var i GetActiveResponseByVolunteerRow
	err := row.Scan(
		&i.ResponseID,
		&i.IncidentID,
		&i.IncidentType,
		&i.Status,
		&i.ReporterLatitude,
		&i.ReporterLongitude,
		&i.AddressDetail,
		&i.AcceptedAt,
	)
	return i, err
}
