// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Incident struct {
	ID                 pgtype.UUID
	ReporterID         pgtype.UUID
	IncidentType       string
	Latitude           pgtype.Numeric
	Longitude          pgtype.Numeric
	Status             pgtype.Text
	UrgencyLevel       pgtype.Text
	ReporterTrustLabel pgtype.Text
	AddressDetail      pgtype.Text
	PhotoPaths         []string
	AudioPath          pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
}

type IncidentResponse struct {
	ID            pgtype.UUID
	IncidentID    pgtype.UUID
	ResponderID   pgtype.UUID
	Status        pgtype.Text
	AcceptedAt    pgtype.Timestamptz
	ArrivedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
	ProofPhotoUrl pgtype.Text
}

type User struct {
	ID    pgtype.UUID
	Email string
}
