services:
  # 1. Database Relasional (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: siagakita_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      # Bind mount ke folder lokal
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - siagakita_network

  # 2. In-Memory & Message Broker (Redis)
  redis:
    image: redis:7-alpine
    container_name: siagakita_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --notify-keyspace-events Ex
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - siagakita_network

  # 3. Server Golang
  backend:
    build:
      context: ../backend-go
      dockerfile: Dockerfile
    container_name: siagakita_backend
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080" # Port API
      - "8081:8081" # Port WebSocket
    depends_on:
      - postgres
      - redis
    networks:
      - siagakita_network

  # 4. pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: siagakita_pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - siagakita_network

networks:
  siagakita_network:
    driver: bridge