// Purpose: Multi-platform Firebase initialization options generated for SiagaKita client applications.
// Data & Logic Flow: Selects platform-specific Firebase configuration and credentials during app bootstrap.
// Key Components: DefaultFirebaseOptions class, platform options (web, android, ios, macos, windows).
//
// Security Architecture Note:
// Firebase API keys embedded below are public client identifiers used exclusively by client SDKs to identify
// the Firebase project within Google services. They do not grant backend administrative privileges.
// In production, these keys are protected via Google Cloud Console API Key Restrictions:
// - Android: Restricted to package name com.siagakita.app and production SHA-1 signing certificates.
// - iOS: Restricted to iOS bundle identifier com.siagakita.app.
// - Web: Restricted to authorized SiagaKita domain referrers and specific enabled APIs.

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHzaTyRzq2jk2in9lWvpZvKTfAGBx1PVM',
    appId: '1:1036281626509:web:cb56a11449ea75fd9e87c4',
    messagingSenderId: '1036281626509',
    projectId: 'siagakita-1557f',
    authDomain: 'siagakita-1557f.firebaseapp.com',
    storageBucket: 'siagakita-1557f.firebasestorage.app',
    measurementId: 'G-507QRXZ0JS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrU56G_7F-ZGqfTbSHROMLM8UoCwCcfCA',
    appId: '1:1036281626509:android:7502d59cb81d149c9e87c4',
    messagingSenderId: '1036281626509',
    projectId: 'siagakita-1557f',
    storageBucket: 'siagakita-1557f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRm0HUJSiv5dnrwnGQimQ-vpzslREHmQI',
    appId: '1:1036281626509:ios:9a910d86ad0d04eb9e87c4',
    messagingSenderId: '1036281626509',
    projectId: 'siagakita-1557f',
    storageBucket: 'siagakita-1557f.firebasestorage.app',
    iosBundleId: 'com.siagakita.app.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRm0HUJSiv5dnrwnGQimQ-vpzslREHmQI',
    appId: '1:1036281626509:ios:6a0e1ac8579aadd79e87c4',
    messagingSenderId: '1036281626509',
    projectId: 'siagakita-1557f',
    storageBucket: 'siagakita-1557f.firebasestorage.app',
    iosBundleId: 'com.example.siagaKita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHzaTyRzq2jk2in9lWvpZvKTfAGBx1PVM',
    appId: '1:1036281626509:web:69fd8fbb922887249e87c4',
    messagingSenderId: '1036281626509',
    projectId: 'siagakita-1557f',
    authDomain: 'siagakita-1557f.firebaseapp.com',
    storageBucket: 'siagakita-1557f.firebasestorage.app',
    measurementId: 'G-2V9PPSLRDY',
  );
}
